services:
  - type: web
    name: locationkhuji-backend
    env: node
    rootDir: apps/backend-api-gateway
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production